# CI workflow runs all source quality tests. It does not build the release binary.
#
name: CI

on:
  push:
    branches: [ main, actions_test ]
  pull_request:
    branches: [ main ]

jobs:
  qc:
    name: Source QC

    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
      BUILD_OPTIONS: --release --features tflite

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.84.0
        components: clippy, rustfmt

    - name: Check source formatting
      run: cargo fmt --check

    - name: Build
      run: cargo build ${{ env.BUILD_OPTIONS }}

    - name: Test
      run: cargo test ${{ env.BUILD_OPTIONS }}

    - name: Clippy
      run: cargo clippy ${{ env.BUILD_OPTIONS }} -- -D warnings

    - name: Clippy on tests
      run: cargo clippy ${{ env.BUILD_OPTIONS }} --tests -- -D warnings
